### ISSUE TITLE
Bug: Incompatibility with MC 1.18.2

### ISSUE THREAD

**Issue by iosgoodch** [The7seVen/Simple_kiln#2]
# Issue
Minecraft 1.82.2 crashes on launch with Simple Kiln installed.

### How reproducible
100% reproducible.

## Additional Information / Resources

---- Minecraft Crash Report ----
[crash-2022-03-11_13.01.32-fml.txt](https://github.com/The7seVen/Simple_kiln/files/8235745/crash-2022-03-11_13.01.32-fml.txt)

<img width="851" alt="Screen Shot 2022-03-11 at 1 08 32 PM" src="https://user-images.githubusercontent.com/9204465/157966961-c3649acb-ca8b-4722-bbea-27c276752d73.png">

**Comment by viidotdev** [comment]
Thanks for the report! Fixed version for 1.18.2 is available on Curseforge, requires JEI 9.5+ (beta).

**Comment by iosgoodch** [comment]
No problem! Verified as fixed.
